# Generated by Django 4.0 on 2023-10-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0003_shop_goods_good_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_goods',
            name='good_kat',
            field=models.CharField(
                choices=[('1', 'Автомобільні шини'), ('2', 'Побутова техніка'), ('3', 'Побутова хімія')], default='',
                max_length=5),
        ),
    ]
