# Generated by Django 4.0 on 2023-10-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0004_alter_shop_goods_good_kat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_goods',
            name='good_kat',
            field=models.CharField(
                choices=[('1', 'Автомобільні шини'), ('2', "Комп'ютери, ноутбуки"), ('3', 'Побутова хімія')],
                default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='shop_goods',
            name='good_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
