# Generated by Django 4.0 on 2023-10-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0005_alter_shop_goods_good_kat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_goods',
            name='good_opys',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='shop_goods',
            name='good_kat',
            field=models.CharField(choices=[('1', 'Автомобільні шини та диски'), ('2', "Комп'ютери  та  ноутбуки, "),
                                            ('3', 'Побутова хімія для дому')], default='', max_length=5),
        ),
    ]
