# Generated by Django 4.0 on 2023-11-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0006_shop_goods_good_opys_alter_shop_goods_good_kat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_goods',
            name='good_name',
            field=models.CharField(max_length=150, verbose_name='Назва товару'),
        ),
    ]
