# Generated by Django 4.0 on 2023-11-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0007_alter_shop_goods_good_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_goods',
            name='good_kat',
            field=models.CharField(choices=[('1', 'Автомобільні шини та диски'), ('2', "Комп'ютери  та  ноутбуки, "),
                                            ('3', 'Побутова хімія для дому')], default='', max_length=5,
                                   verbose_name='Категорія товару'),
        ),
        migrations.AlterField(
            model_name='shop_goods',
            name='good_link',
            field=models.URLField(default='', verbose_name='Посилання на оригінальний товар:'),
        ),
        migrations.AlterField(
            model_name='shop_goods',
            name='good_opys',
            field=models.TextField(default='', verbose_name='Детальний опис товару'),
        ),
        migrations.AlterField(
            model_name='shop_goods',
            name='good_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вартість товару'),
        ),
    ]
