# Generated by Django 4.0 on 2023-11-23 14:12

from django.db import migrations, models

import shop.models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0008_alter_shop_goods_good_kat_alter_shop_goods_good_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_goods',
            name='good_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True,
                                    upload_to=shop.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='shop_goods',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop_goods',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shop_goods',
            name='good_kat',
            field=models.CharField(choices=[('1', 'Автомобільні шини та диски'), ('2', "Комп'ютери  та  ноутбуки"),
                                            ('3', 'Побутова хімія для дому'), ('4', 'Електроінструменти')], default='',
                                   max_length=5, verbose_name='Категорія товару'),
        ),
    ]
