# Generated by Django 4.0 on 2023-11-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0009_shop_goods_good_image_shop_goods_height_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_goods',
            name='height_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shop_goods',
            name='width_field',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
