# Generated by Django 4.0 on 2023-11-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0010_alter_shop_goods_height_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_goods',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shop_goods',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
