# Generated by Django 4.0 on 2023-11-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0011_alter_shop_goods_height_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_goods',
            name='good_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='media/',
                                    width_field='width_field'),
        ),
    ]
